### ISSUE TITLE
to_pairgames throws an error on example in the documentation

### ISSUE THREAD

**Issue by AndyPurvis** [echasnovski/comperes#5]
I'm trying to use comperes and comperank to do some comparisons, but can't get to_pairgames to work. Even the example in the documentation fails:

> cr_data <- data.frame(
+     game = c(rep(1:5, each = 3), 6),
+     player = c(rep(1:5, times = 3), 1),
+     score = 101:116,
+     extraCol = -(1:16)
+ )
> to_pairgames(cr_data)
Error: (converted from warning) All elements of `...` must be named.
Did you want `data = c(player, score)`?

I'm using comperes v 0.2.2 from CRAN with RStudio Version 1.2.5019. Any help very gratefully received!

**Comment by echasnovski** [comment]
Yes, it gave warning (not error) due to change in newer versions of 'tidyr', but outputs were still correct.
Please try the recent 'comperes' 0.2.3 version from CRAN. It should work cleanly.

**Comment by AndyPurvis** [comment]
Thanks for such a quick reply! The outputs weren’t there at all; but updating has fixed the problem - thank you.

Andy
_____________________
Andy Purvis
andy.purvis@nhm.ac.uk<mailto:andy.purvis@nhm.ac.uk>
0207 942 5686

Department of Life Sciences, Natural History Museum, London SW7 5BD, U.K.
Twitter: @AndyPurvisNHM
PREDICTS project: www.predicts.org.uk<http://www.predicts.org.uk>




On 17 Dec 2019, at 10:33, Evgeni Chasnovski <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, it gave warning (not error) due to change in newer versions of 'tidyr', but outputs were still correct.
Please try the recent 'comperes' 0.2.3 version from CRAN. It should work cleanly.
